name: Build and Deploy Backend

on:
  push:
    tags:
      - 'v*'  # Releases: v1.08.24

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Container Registry
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/GCP_PROJECT_ID/backend:${{ github.ref_name }} .
        docker push gcr.io/GCP_PROJECT_ID/backend:${{ github.ref_name }}

    - name: Set up kubectl
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: GCP_PROJECT_ID
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to GKE
      run: |
        kubectl config use-context $(gcloud container clusters list --format "value(name)" --limit 1)
        kubectl set image deployment/backend backend=gcr.io/GCP_PROJECT_ID/backend:${{ github.ref_name }}