name: Build, Analyze and Deploy

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.08.24

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "Logging in to Docker Hub..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      env:
        DEBUG: 1

    - name: Build the Docker image
      run: docker build . -t nodeserver:latest

    - name: List Docker images
      run: docker image ls

    - name: Tag Docker image
      run: docker tag nodeserver:latest devopsport2165/nodeserver:latest

    - name: Push the Docker image to Docker Hub
      run: docker push devopsport2165/nodeserver:latest

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=vishalsubharthi
          -Dsonar.projectKey=CICD
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}