name: Build, Analyze, and Deploy Node.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "Logging in to Docker Hub..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build . -t nodeserver:latest

    - name: List Docker images
      run: docker image ls

    - name: Tag Docker image
      run: docker tag nodeserver:latest devopsport2165/nodeserver:latest

    - name: Push Docker image to Docker Hub
      run: docker push devopsport2165/nodeserver:latest

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=devopsport
          -Dsonar.projectKey=devopsport_devopsport
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: sonarQubeAnalysis

    steps:
    - name: Write SSH private key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        cp private_key.pem ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_PUBLIC_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_ADDRESS }} << 'EOF'
          # Update and install Docker
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker

          # Login to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Pull Docker image
          sudo docker pull devopsport2165/nodeserver:latest

          # Stop and remove existing container
          sudo docker stop nodeserver || true
          sudo docker rm nodeserver || true

          # Run new container
          sudo docker run -d --name nodeserver -p 80:80 devopsport2165/nodeserver:latest
        EOF

  notify-infra-repo:
    runs-on: ubuntu-latest
    needs: deploy-to-ec2

    steps:
    - name: Checkout Infrastructure Repo
      uses: actions/checkout@v3
      with:
        repository: https://github.com/Vishalport/terraform-infrastructure-iac.git  # Replace with your repo
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update Deployment Files
      run: |
        echo "Updating Terraform or Deployment files..."

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update for release ${{ github.sha }}"
        git push origin main