name: Build, Analyze, and Notify

on:
  push:
    branch:
      - 'main'  # Releases: v1.08.24

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "Logging in to Docker Hub..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . -t nodeserver:${{ github.ref_name }}  # Using the tag name as the image tag

    - name: List Docker images
      run: docker image ls

    - name: Tag Docker image
      run: docker tag nodeserver:${{ github.ref_name }} devopsport2165/nodeserver:${{ github.ref_name }}

    - name: Push the Docker image to Docker Hub
      run: docker push devopsport2165/nodeserver:${{ github.ref_name }}

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=devopsport
          -Dsonar.projectKey=devopsport_devopsport
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  notify-infra-repo:
    runs-on: ubuntu-latest
    needs: sonarQubeAnalysis

    steps:
    - name: Checkout Infrastructure Repo
      uses: actions/checkout@v3
      with:
        repository: https://github.com/Vishalport/terraform-infrastructure-iac  # Replace with your repo
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update Deployment Files
      run: |
        echo "Updating Terraform or Deployment files..."

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update for release ${{ github.ref_name }}"
        git push origin main
